In [92]:
import numpy as np
import torch.nn as nn
import torch
import torch.nn as nn
import torch.optim as optim
from MLP_Implementation import MLP

from PyTorch_Vanilla import RNN

In [76]:
# Tensor from a list 
a = torch.tensor([0, 1, 2])

# Tensor from a NumPy array
c = np.ones([2, 3])
c = torch.tensor(c)

# Additional common constructors
x = torch.ones(5, 3)
y = torch.linspace(0, 5, steps = 11)

# We can also compute sums and means of all the elemnts, and also across specific dimensions
z = x.mean(dim = (0, 1))

In [78]:
# Reshaping a Tensor
x = torch.arange(12)
y = x.reshape(-1, 2)

print(y)
print(y.shape)
print(x.data_ptr == y.data_ptr())

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])
torch.Size([6, 2])
False


In [79]:
# Permuting a Tensor
x = torch.rand(3, 48, 64)
y = x.permute(1, 2, 0)
print(y.shape)

# Transposing a Tensor
z = x.transpose(2, 1)
print(z.shape)

torch.Size([48, 64, 3])
torch.Size([3, 64, 48])


In [80]:
# Flatten a tensor
x = torch.arange(12)
y = x.reshape(-1, 2)
z = y.flatten()

print(z)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [81]:
# Unsqueezing a Tensor for broadcasting 
x = torch.rand(2)
y = torch.rand(2, 2)
# z = x * y # results in an error

x = x.unsqueeze(1)
print(x.shape)
z = x*y
print(z)

torch.Size([2, 1])
tensor([[0.0034, 0.0049],
        [0.2350, 0.5288]])


In [82]:
# Concatenation 
x = torch.rand(3, 4)
y = torch.rand(3, 4)
z1 = torch.cat((x, y), dim = 1)

# Stacking
z2 = torch.stack((x, y), dim = 0)
print(z1.shape)
print(z2.shape)

torch.Size([3, 8])
torch.Size([2, 3, 4])


In [83]:
# Vector- vector multiplication
x = torch.rand(5)
y = torch.rand(5)
z = x.dot(y)

In [84]:
net = MLP(4, 8, [32, 16])

x = torch.randn(20, 4)
y = net(x)
print(y.shape)

torch.Size([20, 8])


In [85]:
W = torch.randn(8, 12, requires_grad = True)
x = torch.randn(12)
y = W @ x
z = y.detach()

print(W.requires_gra d)
print(y.requires_grad)

SyntaxError: invalid syntax (2757224832.py, line 6)

In [86]:
# Constructs an MLP with architecture 4 -> 16 -> 2 for solving a binary classificiation problem
net = MLP(4, 2, [16])

# Create synthetic data and feed to network 
inputs = torch.randn(32, 4)
labels = torch.randint(2, size = (32,))

output = net(inputs)

loss_fn = nn.CrossEntropyLoss() # Handles the softmax, which maximizes our log likelihood
loss = loss_fn(output, labels)

In [95]:
net = RNN(4, 16, 8)

x = torch.randn(20, 32, 4)
y,_ = net(x)
print(y.shape)

AttributeError: 'tuple' object has no attribute 'shape'